name: Bug Report
description: Create a report to help improve the program functionality
title: "[Bug]: "
labels: ["bug"]

body:
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: The problem is ...
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: 1. Go to '...'
        2. Click on '....'
        3. Do '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: It should be doing ...
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the program are you running?
      placeholder: I'm on the latest version.
    validations:
      required: true
  - type: textarea
    id: settings
    attributes:
      label: Settings
      description: If applicable, add your settings of the program here (if not using defaults, screenshots are fine for this).
    validations:
      required: true
  - type: textarea
    id: extra-attachments
    attributes:
      label: Extra Attachments
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
